### ISSUE TITLE
Making OpenCV crashed my rpi

### ISSUE THREAD

**Issue by r-luo** [ian-whitestone/rpi-setup#2]
My rpi crashed during `make -j -l 2` at 97%... Retried with `make -j 2 -l 2` and finished fine

`- Richard`

**Comment by ian-whitestone** [comment]
Weird, can't remember what these params actually do but added a reference to this issue in the docs. Thanks for calling out.

**Comment by r-luo** [comment]
`-j` specifies how many threads you use to `make`. I think if you leave it empty it means to use all available threads.
